version: '3.7'
services:
  
  rabbitmq:
    image: rabbitmq:3.8.2-management    
    ports:
      - "5672:5672"
      - "15672:15672"    
    restart: always
    volumes:      
      - ../rabbitmq:/var/lib/rabbitmq/mnesia:rw
      - ./beacon-engine/docker-files/definitions.json:/opt/definitions.json:ro
      - ./beacon-engine/docker-files/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    networks:
      - beacon-network
    healthcheck:
      test: CMD rabbitmq-diagnostics -q check_port_connectivity
      interval: 1m30s
      timeout: 1m
      retries: 5
      start_period: 1m
  
  mysql-beacon-db:
    image: mysql:5.7     
    ports:
      - "3306:3306"
    restart: always
    environment:   
      MYSQL_ROOT_PASSWORD: ZT9HHR953OJRFANH      
      MYSQL_DATABASE: beacon_input
    volumes:
      - mysql-beacon-data-volume:/var/lib/mysql
      - ./beacon-engine/docker-files/provision/mysql/init:/docker-entrypoint-initdb.d
      - ./conf/mysql/:/etc/mysql/conf.d/:ro
    networks:
      - beacon-network
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h", "localhost"]
      interval: 1m30s
      timeout: 1m
      retries: 5
      start_period: 1m
  
  beacon-input:
    build: ./beacon-input
    #ports:
      #- "8091:8091"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: default
      RDS_HOSTNAME: mysql-beacon-db
      RDS_PORT: 3306
      RDS_DB_NAME: beacon_input
      RDS_USERNAME: root
      RDS_PASSWORD: ZT9HHR953OJRFANH
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      BEACON_RABBIT_HOSTNAME: rabbitmq
    depends_on: # Start the depends_on first
      - mysql-beacon-db
      - rabbitmq
    networks:
      - beacon-network
      
  beacon-engine:
    build: ./beacon-engine
    #ports:
      #- "8081:8081"
    restart: always    
    environment:
      RDS_HOSTNAME: mysql-beacon-db
      RDS_PORT: 3306
      RDS_DB_NAME: beacon2
      RDS_USERNAME: root
      RDS_PASSWORD: ZT9HHR953OJRFANH
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672      
      BEACON_RABBIT_HOSTNAME: rabbitmq
      BEACON_NUMBER_OF_ENTROPY_SOURCES: 1           
      BEACON_MAIL_TEST_CONNECTION: "false"
      BEACON_SEND_ALERTS_BY_EMAIL: "false"
      BEACON_X509_CERTIFICATE: docker-files/beacon.cer
      BEACON_X509_PRIVATEKEY: docker-files/beacon-priv.pem
      BEACON_ENGINE_LOG_LEVEL: warn
      BEACON_X509_FOLDER:
    depends_on: # Start the depends_on first
      - rabbitmq
      - mysql-beacon-db
    networks:
      - beacon-network 
      
  beacon-interface:
    build: ./beacon-interface
    ports:
      - "8080:8080"
    restart: always    
    environment:
      RDS_HOSTNAME: mysql-beacon-db
      RDS_PORT: 3306
      RDS_DB_NAME: beacon2
      RDS_USERNAME: root
      RDS_PASSWORD: ZT9HHR953OJRFANH
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672      
      BEACON_RABBIT_HOSTNAME: rabbitmq      
      BEACON_X509_CERTIFICATE: docker-files/beacon.cer
      BEACON_X509_PRIVATEKEY: docker-files/beacon-priv.pem
      BEACON_ENGINE_LOG_LEVEL: warn
      BEACON_X509_FOLDER:
    depends_on: # Start the depends_on first
      - beacon-engine
    networks:
      - beacon-network 

volumes:
  mysql-beacon-data-volume:
  
  
# Networks to be created to facilitate communication between containers
networks:
  beacon-network: