version: '3.7'
services:
  
  rabbitmq:
    image: rabbitmq:3.12.7-management-alpine 
    ports:
      - "5672:5672"
      - "15672:15672"    
    restart: always
    volumes:      
      - ../rabbitmq:/var/lib/rabbitmq/mnesia:rw
      - ./beacon-engine/docker-files/definitions.json:/opt/definitions.json:ro
      - ./beacon-engine/docker-files/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      #- ./conf/healthcheck/health_rabbitmq.sh:/usr/local/bin/health_rabbitmq.sh
    networks:
      - beacon-network
    healthcheck:
      test: rabbitmq-diagnostics -q listeners
      retries: 10
    
  
  mysql-beacon-db:
    image: mariadb:10.11 #1st mysql:5.7-> 8.0.34   mysql:5.75.7 -> mariadb:10.4 e mariadb:10.6   e  mariadb:10.11  
    ports:
      - "3306:3306"
    restart: always
    environment:   
      MYSQL_ROOT_PASSWORD: ZT9HHR953OJRFANH      
      MYSQL_DATABASE: beacon_input
      MARIADB_MYSQL_LOCALHOST_USER: 1
    volumes:
      - mysql-beacon-data-volume:/var/lib/mysql
      - ./beacon-engine/docker-files/provision/mysql/init:/docker-entrypoint-initdb.d
      - ./conf/mysql/:/etc/mysql/conf.d/:ro
      #- ./conf/healthcheck/health_mysql.sh:/usr/local/bin/health_mysql.sh
    networks:
      - beacon-network
    healthcheck:
      test: healthcheck.sh --su-mysql --connect
      retries: 5
  
  beacon-input:
    build: ./beacon-input
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: default
      RDS_HOSTNAME: mysql-beacon-db
      RDS_PORT: 3306
      RDS_DB_NAME: beacon_input
      RDS_USERNAME: root
      RDS_PASSWORD: ZT9HHR953OJRFANH
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      BEACON_RABBIT_HOSTNAME: rabbitmq
    depends_on: # Start the depends_on first
      rabbitmq:
        condition: service_healthy
      mysql-beacon-db:
        condition: service_healthy
    networks:
      - beacon-network
      
  beacon-engine:
    build: ./beacon-engine
    restart: always    
    environment:
      RDS_HOSTNAME: mysql-beacon-db
      RDS_PORT: 3306
      RDS_DB_NAME: beacon2
      RDS_USERNAME: root
      RDS_PASSWORD: ZT9HHR953OJRFANH
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672      
      BEACON_RABBIT_HOSTNAME: rabbitmq
      BEACON_NUMBER_OF_ENTROPY_SOURCES: 1           
      BEACON_MAIL_TEST_CONNECTION: "false"
      BEACON_SEND_ALERTS_BY_EMAIL: "false"
      BEACON_X509_CERTIFICATE: docker-files/beacon.cer
      BEACON_X509_PRIVATEKEY: docker-files/beacon-priv.pem
      BEACON_ENGINE_LOG_LEVEL: warn
      BEACON_X509_FOLDER:
    depends_on: # Start the depends_on first
      rabbitmq:
        condition: service_healthy
      mysql-beacon-db:
        condition: service_healthy
    networks:
      - beacon-network 
      
  beacon-interface:
    build: ./beacon-interface
    #ports:
      #- "8080:8080"
    restart: always    
    environment:
      RDS_HOSTNAME: mysql-beacon-db
      RDS_PORT: 3306
      RDS_DB_NAME: beacon2
      RDS_USERNAME: root
      RDS_PASSWORD: ZT9HHR953OJRFANH
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672      
      BEACON_RABBIT_HOSTNAME: rabbitmq      
      BEACON_X509_CERTIFICATE: docker-files/beacon.cer
      BEACON_X509_PRIVATEKEY: docker-files/beacon-priv.pem
      BEACON_ENGINE_LOG_LEVEL: info
      BEACON_X509_FOLDER: /beacon/certificate
    volumes:
      - ./conf/certificate:/beacon/certificate
    depends_on: # Start the depends_on first
      - beacon-engine
    networks:
      - beacon-network 
      
  beacon-interface-1:
    build: ./beacon-interface
    #ports:
      #- "8081:8080"
    restart: always    
    environment:
      RDS_HOSTNAME: mysql-beacon-db
      RDS_PORT: 3306
      RDS_DB_NAME: beacon2
      RDS_USERNAME: root
      RDS_PASSWORD: ZT9HHR953OJRFANH
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672      
      BEACON_RABBIT_HOSTNAME: rabbitmq      
      BEACON_X509_CERTIFICATE: docker-files/beacon.cer
      BEACON_X509_PRIVATEKEY: docker-files/beacon-priv.pem
      BEACON_ENGINE_LOG_LEVEL: info
      BEACON_X509_FOLDER: /beacon/certificate
      beacon_combination_enabled: false
      beacon_unicorn_enabled: false
    volumes:
      - ./conf/certificate:/beacon/certificate
    depends_on: # Start the depends_on first
      - beacon-engine
    networks:
      - beacon-network
  proxy:
    image: nginx:1.24.0-alpine-slim
    ports:
      - "443:443"
      - "80:80"
    restart: always    
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d/
    depends_on: # Start the depends_on first
      - beacon-interface
      - beacon-interface-1
    networks:
      - beacon-network 

volumes:
  mysql-beacon-data-volume:
  
  
# Networks to be created to facilitate communication between containers
networks:
  beacon-network: