apiVersion: v1
kind: ConfigMap
metadata:
  name: beacon-interface-config
  namespace: beacon
data:
  application-prod.properties: |-
    server.port=8080
    
    beacon.url=https://beacon-d.inmetro.gov.br
    beacon.url.version = 2.1
    
    #Database
    spring.datasource.url=jdbc:mysql://localhost/beacon2?useSSL=false&useTimezone=false&serverTimezone=UTC
    spring.datasource.username=root
    spring.datasource.password=
    
    spring.jpa.hibernate.ddl-auto=validate
       
    
    #hibernate
    spring.jpa.show-sql=false
    
    spring.jpa.properties.hibernate.use_sql_comments=true
    spring.jpa.properties.hibernate.format_sql=true
    
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
    spring.jpa.properties.hibernate.jdbc.time_zone=UTC
    
    #spring
    spring.jpa.open-in-view=false
    #spring.devtools.livereload.port=13579
    
    
    #jackson
    #spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSz
    #spring.jackson.serialization.write-dates-as-timestamps=false
    spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
    
    #logging
    #logging.file=logs/beacon-interface.log
    logging.level.root=warn
    spring.main.banner-mode=off
    
    #########################################################################
    #Generic vdf configurations
    #########################################################################
    #XOR or CONCAT
    vdf.combination=CONCAT
    
    #Local RNG
    #NativePRNG or SHA1PRNG
    #Use NativePRNG for Linux or SHA1PRNG for windows server
    vdf.seed.rng=NativePRNG
    
    #Parameter P   # Configurar depois
    #vdf.parameter.p=9325099249067051137110237972241325094526304716592954055103859972916682236180445434121127711536890366634971622095209473411013065021251467835799907856202363
    
    ##key
    #beacon.x509.certificate=/var/beacon/engine/keys/4096-module/beacon.cer
    #beacon.x509.privatekey=/var/beacon/engine/keys/4096-module/beacon-priv.pem
    beacon.x509.certificate=/var/beacon/conf/certificate/beacon.cer
    beacon.x509.privatekey=/var/beacon/conf/key/beacon-priv.pem
    
        
    beacon.x509.certificate.folder=var/beacon/conf/certificate}
    #########################################################################
    #vdf combination specific parameters
    #########################################################################
    
    #170000 = 18s
    #1133333= 2min
    #1700000 = 3min
    
    # 5 minutos=1955771
    # cada minuto tem 391154
    # 1955771 - (391154*2) = 1173463
    beacon.combination.iterations=1173463
    #period in milliseconds
    beacon.combination.period=600000
    beacon.combination.enabled = ${beacon_combination_enabled:true}
    beacon.combination.delay=0:10
    
    anu.quantum.cron = * 54,55,56 7,15,23 * * ? *
    
    
    #########################################################################
    #vdf unicorn specific parameters
    #########################################################################
    
    # cron style config
    #beacon.unicorn.start.submission=0 0,30 * * * *
    #beacon.unicorn.start.submission=0 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,48,44,46,48,50,52,54,56,58 * * * *
    #beacon.unicorn.start.submission=0 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59 * * * *
    beacon.unicorn.start.submission=0 0,10,20,30,40,50 * * * *
    #beacon.unicorn.start.submission=0 0,30 * * * *
    
    #use comma-separated numbers
    #beacon.unicorn.end.submission=1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59
    
    #170000 = 1 minute running
    #170000*24 = 1530000
    # beacon.unicorn.iterations=1955771
    beacon.unicorn.iterations=1173463
    #period in milliseconds
    beacon.unicorn.period=600000
    beacon.unicorn.enabled=${beacon_unicorn_enabled:true}
    
    
    #########################################################################
    #queue
    spring.rabbitmq.host=localhost
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=user_consumer
    spring.rabbitmq.password=
    
    server.servlet.session.tracking-modes=cookie
    
    #############################################################################
    #cache
    spring.cache.jcache.config=classpath:ehcache.xml
    
    #############################################################################
    #spring aop
    beacon.aspects.enabled=false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon-interface-deployment
  namespace: beacon
  labels:
    app: beacon-interface-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacon-interface-deployment
  template:
    metadata:
      #annotations:
      #  sidecar.istio.io/inject: "true"
      labels:
        app: beacon-interface-deployment
    spec:
      containers:
        - name: beacon-interface-deployment
          image: registro-docker.inmetro.gov.br/inmetro/beacon/beacon-interface:1
          imagePullPolicy: Always # mudar em producao
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          volumeMounts:
            - mountPath: beacon/config
              name: app-vol
      volumes:
        - name: app-vol
          configMap:
            name: beacon-interface-config
      imagePullSecrets:
        - name: inmetro-registry
      nodeSelector:
        applicationType: oltp
---
apiVersion: v1
kind: Service
metadata:
  name: beacon-interface-service
  namespace: beacon
spec:
  selector:
    app: beacon-interface-service
  type: NodePort
  ports:
    - protocol: TCP
      # service port
      port: 8080
      # POD port
      targetPort: 8080